---
title: "Lista 2 MLG"
author: "Davi Wentrick Feijó"
date: "2023-10-02"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Q1. Considere os dados sobre a qualidade do vinho tinto, apresentados no ficheiro `Q01-data.txt`. Ajuste o modelo de regressao linear multipla, e faca uma analise completa desses dados. Que conclusoes voce tira dessa an´alise? (use 5% de significancia durantes as analises)

Com base no conjunto de dados, e possıvel observar que algumas covariaveis estao fortemente correlacionadas. Assim, pede-se:

##### (a) Proponha algum metodo para resolver o problema da multicolinearidade no conjunto de dados.

##### (b) Usando algum metodo de selecao de variaveis, obtenha o modelo final para o conjunto de dados.

##### (c) Apresente a tabela da Analise de Variancia para testar a significancia global dos coeficientes do modelo final. Apresente as hip´otese de teste, e conclua.

##### (d) Com base no modelo obtido no item anterior, faca uma analise de resıduos e conclua.


#### Q02. Uma equipe de pesquisadores de saude mental deseja comparar tres metodos de tratamento da depressao grave (A, B e C=referencia). Eles tambem gostariam de estudar a relacao entre idade e eficacia do tratamento, bem como a interacao (se houver) entre idade e tratamento. Cada elemento da amostra aleatoria simples de 36 pacientes, foi selecionado aleatoriamente para receber o tratamento A, B ou C. Os dados obtidos podem ser encontrados no ficheiro `Q02-data.txt`. A variavel dependente y e a eficacia do tratamento; as variaveis independentes sao: a idade do paciente no aniversario mais proximo, e o tipo de tratamento administrado (use 1% de significancia durantes as analises).

##### (a) Ajuste o modelo de regressao linear e interprete os resultados obtidos.

##### (b) Obtenha a tabela ANOVA para o modelo obtido no item (a) e interprete os resultados.

##### (c) Considere a possibilidade de incluir a interacao entre as varaveis independentes, i.e., assuma que o modelo a ser ajustado tem a seguinte formulacao: $yi =  \beta_0 +  \beta_1x_{1i} +  \beta_2x_{Ai} +  \beta_3x_{Bi} +  \beta_4x_{1i}x_{Ai} + \beta_5x_{1i}x_{Bi} + \epsilon_i$ , com a suposicao de que $\epsilon_i$ ~ $N(0, \sigma^2)$. Com base no modelo anterior,
+ (i) Liste todos os possıveis submodelos que podem ser obtidos usando o modelo apresentado anteriormente.
+ (ii) Interprete os coeficientes de regressao associados aos fatores de interacao.
+ (iii) Apresente a tabela anova para testar as seguintes hipoteses, $H0 : \beta_1 = \beta_4 = \beta_5 = 0$ contra $H1 : \exists \beta_j 6= 0$, com $j = 1, 4, 5$.
+ (iv) Faca uma analise completa dos res´ıduos do modelo.
















